BUAA-BDA/OpenHuFu

backend/pom.xml
backend/src/main/java/com/hufudb/onedb/backend/config/BackendConfiguration.java
backend/src/main/java/com/hufudb/onedb/backend/config/SpringDocConfig.java
backend/src/main/java/com/hufudb/onedb/backend/controller/OwnerController.java
backend/src/main/java/com/hufudb/onedb/backend/controller/UserController.java
build/script/package.sh

Add springdoc to backend and move java files to different folder.

Add springdoc to backend and move java files to different folder

---

build/script/package.sh

Clear old static directory before copy frontend files.

fix package.sh (clear old static directory before copy frontend files)

---

backend/pom.xml
backend/src/main/java/com/hufudb/onedb/backend/BackendApplication.java
backend/src/main/java/com/hufudb/onedb/backend/controller/SqlRecordController.java
backend/src/main/java/com/hufudb/onedb/backend/controller/UserController.java
backend/src/main/java/com/hufudb/onedb/backend/entity/SqlRecord.java
backend/src/main/java/com/hufudb/onedb/backend/generator/CodeGenerator.java
backend/src/main/java/com/hufudb/onedb/backend/mapper/SqlRecordMapper.java
backend/src/main/java/com/hufudb/onedb/backend/service/SqlRecordService.java
backend/src/main/java/com/hufudb/onedb/backend/service/impl/SqlRecordServiceImpl.java
backend/src/main/java/com/hufudb/onedb/backend/utils/Page.java
backend/src/main/java/com/hufudb/onedb/backend/utils/PageUtils.java
backend/src/main/java/com/hufudb/onedb/backend/utils/Pagination.java
backend/src/main/java/com/hufudb/onedb/backend/utils/RecordRequest.java
backend/src/main/resources/db/migration/V1__hufu-ddl.sql
backend/src/main/resources/mapper/SqlRecordMapper.xml
release/demo/config/server1.properties
release/demo/config/server2.properties
release/demo/config/server3.properties

finish sql monitor

---

webapp/src/assets/i18n/languages/en_US.js
webapp/src/assets/i18n/languages/zh_CN.js
webapp/src/pages/operation/operation.vue

operation module (sql record) finished

[frontend] operation module (sql record) finished

---

.github/workflows/ci.yml
.github/workflows/sonarcloud.yml
build/script/sonarcloud.sh
pom.xml

Add sonarcloud configurations.

Add sonarcloud configurations

---

.github/workflows/sonarcloud.yml

Remove manually sonar analysis

Remove manually sonar analysis

---

backend/src/main/java/com/hufudb/onedb/backend/controller/SqlRecordController.java
backend/src/main/java/com/hufudb/onedb/backend/utils/PageUtils.java

sqlRecord page order By id desc

page orderby id desc

---

benchmark/src/main/java/com/hufudb/onedb/TPCHBenchmark.java
core/src/main/java/com/hufudb/onedb/core/implementor/UserSideImplementor.java
core/src/main/java/com/hufudb/onedb/core/zk/DBZkClient.java
core/src/main/java/com/hufudb/onedb/core/zk/OneDBZkClient.java
core/src/main/java/com/hufudb/onedb/core/zk/ZkClient.java
core/src/main/java/com/hufudb/onedb/core/zk/watcher/SchemaWatcher.java
data/src/main/java/com/hufudb/onedb/data/storage/MultiSourceDataSet.java
mpc/src/main/java/com/hufudb/onedb/mpc/gmw/GMW.java
mpc/src/main/java/com/hufudb/onedb/mpc/utils/Stream.java
owner/src/main/java/com/hufudb/onedb/owner/OwnerServer.java
rpc/src/main/java/com/hufudb/onedb/rpc/concurrent/ConcurrentBuffer.java

Fix sonar bugs

---

webapp/src/assets/i18n/languages/en_US.js
webapp/src/assets/i18n/languages/zh_CN.js
webapp/src/pages/datasource/datasource.vue

Add datasource configuration page

---

webapp/src/pages/operation/operation.vue

fix width problem, set status selector clearable, get the data when fresh the page

[front end] operation module fix bug 

---

core/pom.xml
data/src/main/java/com/hufudb/openhufu/data/storage/ArrayRow.java
data/src/main/java/com/hufudb/openhufu/data/storage/Row.java
data/src/main/java/com/hufudb/openhufu/data/storage/SortedDataSet.java
data/src/main/java/com/hufudb/openhufu/data/storage/utils/CompareUtils.java
owner/pom.xml
owner/src/main/java/com/hufudb/openhufu/owner/OwnerService.java
plan/pom.xml
plan/src/main/java/com/hufudb/openhufu/interpreter/Interpreter.java
pom.xml

Fix soanrbugs and dependabot alerts

Fix soanrbugs and dependabot alerts

---

adapter/adapter-csv/pom.xml
adapter/pom.xml
benchmark/pom.xml
benchmark/src/main/java/com/hufudb/openhufu/benchmark/Main.java
benchmark/src/main/java/com/hufudb/openhufu/benchmark/Student.java
benchmark/src/main/java/com/hufudb/openhufu/benchmark/annotation/HandlingTime.java
benchmark/src/main/java/com/hufudb/openhufu/benchmark/annotation/HandlingTimeAspect.java
benchmark/src/main/resources/META-INF/aop.xml
core/pom.xml
data/pom.xml
mpc/pom.xml
owner/pom.xml
plan/pom.xml
platform/pom.xml
pom.xml
proto/pom.xml

Add Time Aspect

---

common/pom.xml
common/src/main/java/com/hufudb/openhufu/common/Main.java
common/src/main/java/com/hufudb/openhufu/common/exception/BaseErrorCode.java
common/src/main/java/com/hufudb/openhufu/common/exception/BaseException.java
common/src/main/java/com/hufudb/openhufu/common/exception/ErrorCode.java
common/src/main/java/com/hufudb/openhufu/common/exception/MessageEntity.java
common/src/main/java/com/hufudb/openhufu/common/exception/OpenHuFuException.java
common/src/main/java/com/hufudb/openhufu/common/metrics/aspect/HandlingTime.java
common/src/main/java/com/hufudb/openhufu/common/metrics/aspect/HandlingTimeAspect.java
core/src/main/java/com/hufudb/openhufu/core/implementor/UserSideImplementor.java
core/src/main/java/com/hufudb/openhufu/core/sql/rel/OpenHuFuToEnumerableConverter.java
mpc/src/main/java/com/hufudb/openhufu/mpc/gmw/GMW.java
mpc/src/main/java/com/hufudb/openhufu/mpc/lib/LibraryLoader.java
mpc/src/main/java/com/hufudb/openhufu/mpc/ot/PublicKeyOT.java
owner/src/main/java/com/hufudb/openhufu/owner/OwnerService.java
owner/src/main/java/com/hufudb/openhufu/owner/adapter/AdapterLoader.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/OwnerSideImplementor.java
plan/src/main/java/com/hufudb/openhufu/expression/CusAggFuncFactory.java

Fix sonarcloud security hotspots

Fix sonarcloud security hotspots

---

common/src/main/java/com/hufudb/openhufu/common/exception/OpenHuFuException.java

Fix sonarcloud bug

---

README.md

add resource to readme

---

.gitignore
README.md
build/script/benchmark.sh
build/script/extract_tpc_h.sh
dataset/genSyntheticData.py

add data generation shell and readme

add data generation shell and readme

---

owner/pom.xml
owner/src/main/java/com/hufudb/openhufu/owner/config/ImplementorConfig.java

fix CVE-2022-1471

---

benchmark/src/main/resources/endpoints.json
benchmark/src/main/resources/tables.json
benchmark/src/test/java/com/hufudb/openhufu/benchmark/OpenHuFuBenchmarkTest.java
common/src/main/java/com/hufudb/openhufu/common/exception/ErrorCode.java
owner/src/main/java/com/hufudb/openhufu/owner/config/ImplementorConfig.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/OwnerImplementorFactory.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/OwnerSideImplementor.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/join/HashEqualJoin.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/join/OwnerJoin.java
owner/src/main/java/com/hufudb/openhufu/owner/user/OpenHuFuUser.java
owner/src/main/resources/owner1.yml
plan/pom.xml
plan/src/main/java/com/hufudb/openhufu/udf/UDFLoader.java
release/owner.sh
release/owner_all.sh

add join interface

---

benchmark/src/test/java/com/hufudb/openhufu/benchmark/OpenHuFuBenchmarkTest.java

fix small test bugs in OpenHuFUBenchmarkTest

fix small test bugs in OpenHuFUBenchmarkTest

---

benchmark/src/test/java/com/hufudb/openhufu/benchmark/OpenHuFuSpatialBenchmarkTest.java
common/src/main/java/com/hufudb/openhufu/common/exception/ErrorCode.java
owner/pom.xml
plan/src/main/java/com/hufudb/openhufu/expression/AggFuncType.java
plan/src/main/java/com/hufudb/openhufu/udf/ScalarUDF.java
pom.xml
udf/spatial-udf/src/main/java/com/hufudb/openhufu/udf/DWithin.java
udf/spatial-udf/src/main/java/com/hufudb/openhufu/udf/Distance.java
udf/spatial-udf/src/main/java/com/hufudb/openhufu/udf/Point.java
user/pom.xml

format spatial udf code

---

owner/src/main/java/com/hufudb/openhufu/owner/OwnerServer.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/aggregate/OwnerAggregateFunction.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/aggregate/sum/GMWSum.java
owner/src/main/java/com/hufudb/openhufu/owner/implementor/aggregate/sum/SecretSharingSum.java

move variable sum to sub class

move variable sum to sub class

---

.github/workflows/build-ci.yml
.github/workflows/deploy-ci.yml

optimize github workflow

---

README.md
benchmark/pom.xml
release/benchmark.sh
scripts/build/package.sh
scripts/test/benchmark.sh

add instructions in README
#136

add instructions in README

---

.github/workflows/build-ci.yml
.github/workflows/deploy-ci.yml

update github workflow

---

.github/workflows/deploy-ci.yml

fix bugs when deploy OpenHuFu

---

README.md
benchmark/src/main/java/com/hufudb/openhufu/benchmark/OpenHuFuBenchmark.java
benchmark/src/test/java/com/hufudb/openhufu/benchmark/OpenHuFuBenchmarkTest.java
benchmark/src/test/java/com/hufudb/openhufu/benchmark/OpenHuFuSpatialBenchmarkTest.java
benchmark/src/test/java/com/hufudb/openhufu/benchmark/OpenHuFuTPCHTest.java
core/src/main/java/com/hufudb/openhufu/core/implementor/UserSideImplementor.java
core/src/main/java/com/hufudb/openhufu/core/rewriter/BasicRewriter.java
plan/src/main/java/com/hufudb/openhufu/plan/BasePlan.java
user/src/main/java/com/hufudb/openhufu/user/OpenHuFuUser.java
user/src/test/java/com/hufudb/openhufu/user/OpenHuFuUserTest.java

remove function executeSql(String sql) in OpenHuFuUser

remove function executeSql(String sql) in OpenHuFuUser

---

mpc/src/main/java/com/hufudb/openhufu/mpc/lib/aby/AbyWrapper.java
mpc/src/main/java/com/hufudb/openhufu/mpc/lib/aby/MultiCmp.java
mpc/src/test/java/com/hufudb/openhufu/mpc/elgamal/ElgamalTest.java
mpc/src/test/java/com/hufudb/openhufu/mpc/gmw/GMWTest.java
mpc/src/test/java/com/hufudb/openhufu/mpc/lib/LibraryLoaderTest.java
mpc/src/test/java/com/hufudb/openhufu/mpc/lib/aby/MultiCmpTest.java
mpc/src/test/java/com/hufudb/openhufu/mpc/psi/HashPSITest.java
mpc/src/test/java/com/hufudb/openhufu/mpc/secretsharing/SecretSharingTest.java
mpc/src/test/java/com/hufudb/openhufu/mpc/utils/UtilTest.java
proto/src/main/proto/plan.proto

modify interface for aby
add 2-party max function (can be extended to multi-party)
ignore the brittle tests in package mpc

2-party max function

---

docker/Dockerfile
scripts/build/image.sh
scripts/build/setup_docker.sh
scripts/build/stop_docker.sh

dockered owner

---

Dockerfile
scripts/build/image.sh
scripts/build/setup_docker.sh
scripts/build/stop_docker.sh

之前提交到main分支了，现在重新提交到hufu-wxy分支

add hufu image

---

hufu-mysql-driver/src/main/java/group/bda/federate/driver/utils/MysqlIRTranslator.java

fix bugs for distance function not exists in mysql8.0+

---

README.md

Update the related work paper lists.

Update related works in README.md
